# Generated by Django 3.2 on 2021-12-18 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0004_rename_notes_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('medication', models.CharField(max_length=500)),
                ('filled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('prescribed_on', models.DateTimeField(auto_now_add=True)),
                ('filled_on', models.DateTimeField(blank=True, default=None)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('filled_by', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
