# Generated by Django 3.2 on 2021-12-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='filled_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
