# Generated by Django 3.2 on 2021-12-18 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0007_auto_20211218_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='filled',
            new_name='is_filled',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='filled_by',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='filled_on',
        ),
        migrations.AddField(
            model_name='prescription',
            name='expires_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Filled',
            fields=[
                ('notes', models.TextField(blank=True, null=True)),
                ('filled_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('filled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.prescription')),
            ],
        ),
    ]
