# Generated by Django 3.2 on 2021-12-18 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20211218_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filled',
            name='filled_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
