# Generated by Django 3.2 on 2021-12-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_filled_filled_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='vote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
