# Generated by Django 3.2 on 2021-12-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_patient_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='value',
            field=models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=200),
        ),
    ]
