# Generated by Django 3.2 on 2021-12-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_alter_note_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filled',
            name='prescription',
        ),
        migrations.AddField(
            model_name='patient',
            name='fills',
            field=models.ManyToManyField(blank=True, to='patients.Filled'),
        ),
    ]
