# Generated by Django 3.2 on 2021-12-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_auto_20211226_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='upc',
            field=models.CharField(default='1345-7654-193307', max_length=500),
        ),
        migrations.AlterField(
            model_name='note',
            name='value',
            field=models.CharField(choices=[('down', 'Down Vote'), ('up', 'Up Vote')], max_length=200),
        ),
    ]
